services:
  - type: web
    name: first-aid-expert-system
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y swi-prolog
      pip install -r requirements.txt
    startCommand: python app.py
    branch: deploy
